services:
    finansoapp:
        container_name: "finansoapp"
        image: mkordowiak/finanso-app
        build:
            context: .
            dockerfile: FinansoApp/Dockerfile
        ports:
            - "8080:8080"
            - "8081:8081"
        environment:
            ConnectionStrings__DefaultConnection: "Server=finansoapp-db;Database=finansoDB;User Id=sa;Password=!Password2137*;TrustServerCertificate=True"
        depends_on:
            - finansoapp-db
    finansoapp-db:
        image: "mcr.microsoft.com/mssql/server:latest"
        container_name: "finansoapp-db"
        environment:
            SA_PASSWORD: "!Password2137*"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
            - mssql_data:/var/opt/mssql
  
volumes:
  mssql_data: