name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore FinansoApp.sln

    - name: Install dependencies
      run: dotnet tool restore

    - name: Test FinansoApp
      run: dotnet test ./FinansoApp.Tests --logger "trx;LogFileName=FinansoApp_test_results.xml" --collect:"XPlat Code Coverage"

    - name: Test FinansoData
      run: dotnet test ./FinansoData.Tests --logger "trx;LogFileName=FinansoData_test_results.xml" --collect:"XPlat Code Coverage"